# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_rating', models.FloatField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_prediction_fk', to='app.Movie')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prediction_fk', to='app.User')),
            ],
        ),
    ]
