# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recomendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomendation',
            new_name='Recommendation',
        ),
    ]
